### ISSUE TITLE
Kirei Logo for WebComponents.dev

### ISSUE THREAD

**Issue by georges-gomes** [iFaxity/kirei#140]
Hi

I created a template for Kirei in WebComponents.dev

https://webcomponents.dev/edit/h7DjJR9X7TbjAo1EUGe9

I want to add it to the template list

https://webcomponents.dev/new

But I need a logo

Do you have one ?

Thanks

**Comment by iFaxity** [comment]
Cool stuff Georges! I'll get working on it tonight and work something out. :)

**Comment by iFaxity** [comment]
Hey @georges-gomes, the logo is available as an SVG here: https://github.com/iFaxity/kirei/blob/master/logo.svg. If you need it as an image instead i can give you one if you are unable to convert it yourself.

But i have confidence in that you can fix it.

**Comment by georges-gomes** [comment]
Very nice 👌
Coming up soon

![image](https://user-images.githubusercontent.com/5250572/103679018-39408200-4f7c-11eb-9368-411cf94cf552.png)

Do you have a twitter accunt?

**Comment by iFaxity** [comment]
@georges-gomes Great work! No sorry I don't own a twitter account. Not for the project either.

Big thanks for contributing.

**Comment by georges-gomes** [comment]
Forgot to mention but you were live this week:

https://webcomponents.dev/new

https://twitter.com/webcomp_dev/status/1346803880420630537?s=20

https://twitter.com/webcomp_dev/status/1347127278770286592?s=20

👍

Cheers!

**Comment by iFaxity** [comment]
@georges-gomes Very cool!

Thank you very much!
